
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action OpenAction;

	private global::Gtk.Action LoadRomAction;

	private global::Gtk.Action ResetAction;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action ResetAction3;

	private global::Gtk.Action OpenAction1;

	private global::Gtk.Action EmulationAction;

	private global::Gtk.Action ResetAction2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.DrawingArea drawingarea;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("Open.."), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open..");
		w1.Add(this.OpenAction, null);
		this.LoadRomAction = new global::Gtk.Action("LoadRomAction", global::Mono.Unix.Catalog.GetString("Load Rom"), null, null);
		this.LoadRomAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Load Rom");
		w1.Add(this.LoadRomAction, null);
		this.ResetAction = new global::Gtk.Action("ResetAction", global::Mono.Unix.Catalog.GetString("Reset"), null, null);
		this.ResetAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Reset");
		w1.Add(this.ResetAction, null);
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open Rom");
		w1.Add(this.FileAction, null);
		this.ResetAction3 = new global::Gtk.Action("ResetAction3", global::Mono.Unix.Catalog.GetString("Reset"), null, null);
		this.ResetAction3.ShortLabel = global::Mono.Unix.Catalog.GetString("Reset");
		w1.Add(this.ResetAction3, null);
		this.OpenAction1 = new global::Gtk.Action("OpenAction1", global::Mono.Unix.Catalog.GetString("Open"), null, null);
		this.OpenAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
		w1.Add(this.OpenAction1, null);
		this.EmulationAction = new global::Gtk.Action("EmulationAction", global::Mono.Unix.Catalog.GetString("Emulation"), null, null);
		this.EmulationAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Emulation");
		w1.Add(this.EmulationAction, null);
		this.ResetAction2 = new global::Gtk.Action("ResetAction2", global::Mono.Unix.Catalog.GetString("Reset"), null, null);
		this.ResetAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Reset");
		w1.Add(this.ResetAction2, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.drawingarea = new global::Gtk.DrawingArea();
		this.drawingarea.Name = "drawingarea";
		this.vbox3.Add(this.drawingarea);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.drawingarea]));
		w2.Position = 1;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 401;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
